import os

os.makedirs("scripts", exist_ok=True)
os.makedirs("src/utils", exist_ok=True)
os.makedirs("src/ingestion", exist_ok=True)

# ── logger.py ──────────────────────────────────────────────────
logger_code = [
    "import sys\n",
    "from pathlib import Path\n",
    "from loguru import logger\n",
    "\n",
    "def setup_logger(log_level='INFO', log_to_file=True):\n",
    "    logger.remove()\n",
    "    logger.add(\n",
    "        sys.stdout,\n",
    "        level=log_level,\n",
    "        format=(\n",
    "            '<green>{time:YYYY-MM-DD HH:mm:ss}</green> | '\n",
    "            '<level>{level: <8}</level> | '\n",
    "            '<cyan>{name}</cyan>:<cyan>{line}</cyan> | '\n",
    "            '<level>{message}</level>'\n",
    "        ),\n",
    "        colorize=True,\n",
    "    )\n",
    "    if log_to_file:\n",
    "        Path('logs').mkdir(exist_ok=True)\n",
    "        logger.add(\n",
    "            'logs/pipeline_{time:YYYY-MM-DD}.log',\n",
    "            level=log_level,\n",
    "            format='{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{line} | {message}',\n",
    "            rotation='1 day',\n",
    "            retention='30 days',\n",
    "            compression='zip',\n",
    "            enqueue=True,\n",
    "        )\n",
    "    return logger\n",
    "\n",
    "log = setup_logger()\n",
]

# ── exceptions.py ───────────────────────────────────────────────
exceptions_code = [
    "class ForexPipelineError(Exception):\n",
    "    def __init__(self, message, details=None):\n",
    "        super().__init__(message)\n",
    "        self.message = message\n",
    "        self.details = details or {}\n",
    "    def __str__(self):\n",
    "        if self.details:\n",
    "            return f'{self.message} | Details: {self.details}'\n",
    "        return self.message\n",
    "\n",
    "class DataIngestionError(ForexPipelineError): pass\n",
    "class DataValidationError(ForexPipelineError): pass\n",
    "class DataProcessingError(ForexPipelineError): pass\n",
    "class FeatureEngineeringError(ForexPipelineError): pass\n",
    "class ModelTrainingError(ForexPipelineError): pass\n",
    "class ModelLoadError(ForexPipelineError): pass\n",
    "class ModelPredictionError(ForexPipelineError): pass\n",
    "class BacktestError(ForexPipelineError): pass\n",
    "class SharpeThresholdError(ForexPipelineError): pass\n",
    "class PipelineConfigError(ForexPipelineError): pass\n",
]

# ── config.py ───────────────────────────────────────────────────
config_code = [
    "from pathlib import Path\n",
    "import yaml\n",
    "from src.utils.logger import log\n",
    "from src.utils.exceptions import PipelineConfigError\n",
    "\n",
    "def load_config(config_path='configs/config.yaml'):\n",
    "    path = Path(config_path)\n",
    "    if not path.exists():\n",
    "        raise PipelineConfigError(\n",
    "            f'Config file not found at: {config_path}',\n",
    "            details={'expected_path': str(path.absolute())}\n",
    "        )\n",
    "    try:\n",
    "        with open(path, 'r') as f:\n",
    "            config = yaml.safe_load(f)\n",
    "        log.info(f'Configuration loaded from {config_path}')\n",
    "    except yaml.YAMLError as e:\n",
    "        raise PipelineConfigError('Failed to parse config.yaml',\n",
    "            details={'error': str(e)})\n",
    "    required_keys = ['data', 'features', 'models', 'backtesting', 'mlflow']\n",
    "    missing = [key for key in required_keys if key not in config]\n",
    "    if missing:\n",
    "        raise PipelineConfigError('Config missing required sections',\n",
    "            details={'missing_keys': missing})\n",
    "    log.debug(f'Config OK. Sections: {list(config.keys())}')\n",
    "    return config\n",
    "\n",
    "CONFIG = load_config()\n",
]

# ── ingest.py ───────────────────────────────────────────────────
ingest_code = [
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from datetime import datetime, timedelta\n",
    "from typing import Optional\n",
    "from src.utils.logger import log\n",
    "from src.utils.exceptions import DataIngestionError, DataValidationError\n",
    "from src.utils.config import CONFIG\n",
    "\n",
    "MIN_REQUIRED_ROWS = 100\n",
    "MAX_NULL_PCT = 0.05\n",
    "REQUIRED_COLUMNS = ['Open', 'High', 'Low', 'Close', 'Volume']\n",
    "\n",
    "def download_ohlcv(ticker, period_years, interval, end_date=None):\n",
    "    end = end_date or datetime.today()\n",
    "    start = end - timedelta(days=period_years * 365)\n",
    "    log.info(f'Downloading {ticker} | From: {start.date()} To: {end.date()}')\n",
    "    try:\n",
    "        df = yf.download(\n",
    "            tickers=ticker,\n",
    "            start=start.strftime('%Y-%m-%d'),\n",
    "            end=end.strftime('%Y-%m-%d'),\n",
    "            interval=interval,\n",
    "            auto_adjust=True,\n",
    "            progress=False,\n",
    "        )\n",
    "    except Exception as e:\n",
    "        raise DataIngestionError(\n",
    "            f'yfinance download failed for {ticker}',\n",
    "            details={'ticker': ticker, 'error': str(e)}\n",
    "        )\n",
    "    if df is None or df.empty:\n",
    "        raise DataIngestionError(\n",
    "            f'yfinance returned empty data for {ticker}',\n",
    "            details={'ticker': ticker, 'start': str(start.date()), 'end': str(end.date())}\n",
    "        )\n",
    "    log.success(f'Downloaded {len(df)} rows for {ticker}')\n",
    "    return df\n",
    "\n",
    "def validate_ohlcv(df, ticker):\n",
    "    log.info(f'Validating data for {ticker} | Shape: {df.shape}')\n",
    "    if isinstance(df.columns, pd.MultiIndex):\n",
    "        df.columns = df.columns.get_level_values(0)\n",
    "    missing_cols = [c for c in REQUIRED_COLUMNS if c not in df.columns]\n",
    "    if missing_cols:\n",
    "        raise DataValidationError(f'Missing columns in {ticker}',\n",
    "            details={'missing': missing_cols})\n",
    "    if len(df) < MIN_REQUIRED_ROWS:\n",
    "        raise DataValidationError(f'Insufficient data for {ticker}',\n",
    "            details={'rows_found': len(df), 'minimum_required': MIN_REQUIRED_ROWS})\n",
    "    null_pct = df[REQUIRED_COLUMNS].isnull().mean()\n",
    "    violating = null_pct[null_pct > MAX_NULL_PCT]\n",
    "    if not violating.empty:\n",
    "        raise DataValidationError(f'Too many nulls in {ticker}',\n",
    "            details={'null_percentages': violating.to_dict()})\n",
    "    invalid_hl = df[df['High'] < df['Low']]\n",
    "    if not invalid_hl.empty:\n",
    "        raise DataValidationError(f'High < Low found in {ticker}',\n",
    "            details={'first_occurrence': str(invalid_hl.index[0])})\n",
    "    duplicates = df.index.duplicated().sum()\n",
    "    if duplicates > 0:\n",
    "        log.warning(f'Removing {duplicates} duplicate timestamps in {ticker}')\n",
    "        df = df[~df.index.duplicated(keep='last')]\n",
    "    rows_before = len(df)\n",
    "    df = df.dropna(subset=REQUIRED_COLUMNS)\n",
    "    dropped = rows_before - len(df)\n",
    "    if dropped > 0:\n",
    "        log.warning(f'Dropped {dropped} rows with nulls in {ticker}')\n",
    "    log.success(f'Validation passed for {ticker} | Clean rows: {len(df)}')\n",
    "    return df\n",
    "\n",
    "def save_raw_data(df, ticker, raw_path):\n",
    "    clean_ticker = ticker.replace('=X', '').replace('/', '')\n",
    "    output_dir = Path(raw_path)\n",
    "    output_dir.mkdir(parents=True, exist_ok=True)\n",
    "    file_path = output_dir / f'{clean_ticker}_raw.parquet'\n",
    "    try:\n",
    "        df.to_parquet(file_path, index=True)\n",
    "        log.success(f'Saved raw data to {file_path} | Rows: {len(df)}')\n",
    "    except Exception as e:\n",
    "        raise DataIngestionError(f'Failed to save raw data for {ticker}',\n",
    "            details={'path': str(file_path), 'error': str(e)})\n",
    "    return file_path\n",
    "\n",
    "def run_ingestion():\n",
    "    log.info('STARTING DATA INGESTION PIPELINE')\n",
    "    tickers = CONFIG['data']['pairs']\n",
    "    interval = CONFIG['data']['interval']\n",
    "    period_years = CONFIG['data']['period_years']\n",
    "    raw_path = CONFIG['data']['raw_path']\n",
    "    log.info(f'Tickers: {tickers} | Interval: {interval} | Period: {period_years} years')\n",
    "    results = {}\n",
    "    failed = []\n",
    "    for ticker in tickers:\n",
    "        log.info(f'Processing {ticker}...')\n",
    "        try:\n",
    "            raw_df = download_ohlcv(\n",
    "                ticker=ticker,\n",
    "                period_years=period_years,\n",
    "                interval=interval,\n",
    "            )\n",
    "            clean_df = validate_ohlcv(df=raw_df, ticker=ticker)\n",
    "            saved_path = save_raw_data(\n",
    "                df=clean_df,\n",
    "                ticker=ticker,\n",
    "                raw_path=raw_path,\n",
    "            )\n",
    "            results[ticker] = {\n",
    "                'status': 'success',\n",
    "                'rows': len(clean_df),\n",
    "                'path': str(saved_path),\n",
    "                'date_range': f'{clean_df.index.min().date()} to {clean_df.index.max().date()}',\n",
    "            }\n",
    "        except (DataIngestionError, DataValidationError) as e:\n",
    "            log.error(f'Failed to ingest {ticker}: {e}')\n",
    "            results[ticker] = {'status': 'failed', 'error': str(e)}\n",
    "            failed.append(ticker)\n",
    "    log.info('INGESTION SUMMARY')\n",
    "    for ticker, result in results.items():\n",
    "        if result['status'] == 'success':\n",
    "            log.success(f\"OK {ticker} | {result['rows']} rows | {result['date_range']}\")\n",
    "        else:\n",
    "            log.error(f\"FAILED {ticker} | {result['error']}\")\n",
    "    if len(failed) == len(tickers):\n",
    "        raise DataIngestionError('All tickers failed.', details={'failed': failed})\n",
    "    log.info('Data ingestion complete.')\n",
    "    return results\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    run_ingestion()\n",
]

# ── Write all files ─────────────────────────────────────────────
file_map = {
    'src/utils/logger.py':      logger_code,
    'src/utils/exceptions.py':  exceptions_code,
    'src/utils/config.py':      config_code,
    'src/ingestion/ingest.py':  ingest_code,
}

for filepath, lines in file_map.items():
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w', encoding='utf-8', newline='\n') as f:
        f.writelines(lines)
    print(f'Written: {filepath}')


# Fix src/utils/__init__.py
init_code = [
    "from src.utils.logger import log\n",
    "from src.utils.exceptions import (\n",
    "    ForexPipelineError,\n",
    "    DataIngestionError,\n",
    "    DataValidationError,\n",
    "    DataProcessingError,\n",
    "    FeatureEngineeringError,\n",
    "    ModelTrainingError,\n",
    "    ModelLoadError,\n",
    "    ModelPredictionError,\n",
    "    BacktestError,\n",
    "    SharpeThresholdError,\n",
    "    PipelineConfigError,\n",
    ")\n",
]

with open('src/utils/__init__.py', 'w', encoding='utf-8', newline='\n') as f:
    f.writelines(init_code)
print('Fixed: src/utils/__init__.py')

# Add this to scripts/write_files.py

config_yaml = [
    "project:\n",
    "  name: forex-signal-pipeline\n",
    "  version: 1.0.0\n",
    "\n",
    "data:\n",
    "  pairs:\n",
    "    - EURUSD=X\n",
    "  interval: 1d\n",
    "  period_years: 5\n",
    "  raw_path: data/raw\n",
    "  processed_path: data/processed\n",
    "  features_path: data/features\n",
    "\n",
    "features:\n",
    "  rsi_period: 14\n",
    "  macd_fast: 12\n",
    "  macd_slow: 26\n",
    "  macd_signal: 9\n",
    "  bb_period: 20\n",
    "  atr_period: 14\n",
    "  sma_periods: [10, 20, 50]\n",
    "  prediction_horizon: 5\n",
    "\n",
    "models:\n",
    "  prophet:\n",
    "    n_trials: 20\n",
    "  lstm:\n",
    "    n_trials: 10\n",
    "    sequence_length: 20\n",
    "    units: [32, 16]\n",
    "    dropout: 0.2\n",
    "    epochs: 20\n",
    "    batch_size: 32\n",
    "  sklearn:\n",
    "    n_trials: 30\n",
    "  ensemble:\n",
    "    n_weight_trials: 100\n",
    "\n",
    "backtesting:\n",
    "  train_months: 24\n",
    "  test_months: 3\n",
    "  sharpe_threshold: 1.0\n",
    "  risk_free_rate: 0.05\n",
    "\n",
    "mlflow:\n",
    "  tracking_uri: http://127.0.0.1:5000\n",
    "  experiment_name: forex-signal-pipeline\n",
    "  model_registry:\n",
    "    EURUSD: forex-ensemble-EURUSD\n",
    "\n",
    "serving:\n",
    "  host: 0.0.0.0\n",
    "  port: 8000\n",
    "\n",
    "dashboard:\n",
    "  port: 8501\n",
]

with open('configs/config.yaml', 'w', encoding='utf-8', newline='\n') as f:
    f.writelines(config_yaml)
print('Fixed: configs/config.yaml')

print('Done. All files written cleanly.')