import os

os.makedirs("scripts", exist_ok=True)
os.makedirs("src/utils", exist_ok=True)
os.makedirs("src/ingestion", exist_ok=True)

# ── logger.py ──────────────────────────────────────────────────
logger_code = [
    "import sys\n",
    "from pathlib import Path\n",
    "from loguru import logger\n",
    "\n",
    "def setup_logger(log_level='INFO', log_to_file=True):\n",
    "    logger.remove()\n",
    "    logger.add(\n",
    "        sys.stdout,\n",
    "        level=log_level,\n",
    "        format=(\n",
    "            '<green>{time:YYYY-MM-DD HH:mm:ss}</green> | '\n",
    "            '<level>{level: <8}</level> | '\n",
    "            '<cyan>{name}</cyan>:<cyan>{line}</cyan> | '\n",
    "            '<level>{message}</level>'\n",
    "        ),\n",
    "        colorize=True,\n",
    "    )\n",
    "    if log_to_file:\n",
    "        Path('logs').mkdir(exist_ok=True)\n",
    "        logger.add(\n",
    "            'logs/pipeline_{time:YYYY-MM-DD}.log',\n",
    "            level=log_level,\n",
    "            format='{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{line} | {message}',\n",
    "            rotation='1 day',\n",
    "            retention='30 days',\n",
    "            compression='zip',\n",
    "            enqueue=True,\n",
    "        )\n",
    "    return logger\n",
    "\n",
    "log = setup_logger()\n",
]

# ── exceptions.py ───────────────────────────────────────────────
exceptions_code = [
    "class ForexPipelineError(Exception):\n",
    "    def __init__(self, message, details=None):\n",
    "        super().__init__(message)\n",
    "        self.message = message\n",
    "        self.details = details or {}\n",
    "    def __str__(self):\n",
    "        if self.details:\n",
    "            return f'{self.message} | Details: {self.details}'\n",
    "        return self.message\n",
    "\n",
    "class DataIngestionError(ForexPipelineError): pass\n",
    "class DataValidationError(ForexPipelineError): pass\n",
    "class DataProcessingError(ForexPipelineError): pass\n",
    "class FeatureEngineeringError(ForexPipelineError): pass\n",
    "class ModelTrainingError(ForexPipelineError): pass\n",
    "class ModelLoadError(ForexPipelineError): pass\n",
    "class ModelPredictionError(ForexPipelineError): pass\n",
    "class BacktestError(ForexPipelineError): pass\n",
    "class SharpeThresholdError(ForexPipelineError): pass\n",
    "class PipelineConfigError(ForexPipelineError): pass\n",
]

# ── config.py ───────────────────────────────────────────────────
config_code = [
    "from pathlib import Path\n",
    "import yaml\n",
    "from src.utils.logger import log\n",
    "from src.utils.exceptions import PipelineConfigError\n",
    "\n",
    "def load_config(config_path='configs/config.yaml'):\n",
    "    path = Path(config_path)\n",
    "    if not path.exists():\n",
    "        raise PipelineConfigError(\n",
    "            f'Config file not found at: {config_path}',\n",
    "            details={'expected_path': str(path.absolute())}\n",
    "        )\n",
    "    try:\n",
    "        with open(path, 'r') as f:\n",
    "            config = yaml.safe_load(f)\n",
    "        log.info(f'Configuration loaded from {config_path}')\n",
    "    except yaml.YAMLError as e:\n",
    "        raise PipelineConfigError('Failed to parse config.yaml',\n",
    "            details={'error': str(e)})\n",
    "    required_keys = ['data', 'features', 'models', 'backtesting', 'mlflow']\n",
    "    missing = [key for key in required_keys if key not in config]\n",
    "    if missing:\n",
    "        raise PipelineConfigError('Config missing required sections',\n",
    "            details={'missing_keys': missing})\n",
    "    log.debug(f'Config OK. Sections: {list(config.keys())}')\n",
    "    return config\n",
    "\n",
    "CONFIG = load_config()\n",
]

# ── ingest.py ───────────────────────────────────────────────────
ingest_code = [
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from datetime import datetime, timedelta\n",
    "from typing import Optional\n",
    "from src.utils.logger import log\n",
    "from src.utils.exceptions import DataIngestionError, DataValidationError\n",
    "from src.utils.config import CONFIG\n",
    "\n",
    "MIN_REQUIRED_ROWS = 100\n",
    "MAX_NULL_PCT = 0.05\n",
    "REQUIRED_COLUMNS = ['Open', 'High', 'Low', 'Close', 'Volume']\n",
    "\n",
    "def download_ohlcv(ticker, period_years, interval, end_date=None):\n",
    "    end = end_date or datetime.today()\n",
    "    start = end - timedelta(days=period_years * 365)\n",
    "    log.info(f'Downloading {ticker} | From: {start.date()} To: {end.date()}')\n",
    "    try:\n",
    "        df = yf.download(\n",
    "            tickers=ticker,\n",
    "            start=start.strftime('%Y-%m-%d'),\n",
    "            end=end.strftime('%Y-%m-%d'),\n",
    "            interval=interval,\n",
    "            auto_adjust=True,\n",
    "            progress=False,\n",
    "        )\n",
    "    except Exception as e:\n",
    "        raise DataIngestionError(\n",
    "            f'yfinance download failed for {ticker}',\n",
    "            details={'ticker': ticker, 'error': str(e)}\n",
    "        )\n",
    "    if df is None or df.empty:\n",
    "        raise DataIngestionError(\n",
    "            f'yfinance returned empty data for {ticker}',\n",
    "            details={'ticker': ticker, 'start': str(start.date()), 'end': str(end.date())}\n",
    "        )\n",
    "    log.success(f'Downloaded {len(df)} rows for {ticker}')\n",
    "    return df\n",
    "\n",
    "def validate_ohlcv(df, ticker):\n",
    "    log.info(f'Validating data for {ticker} | Shape: {df.shape}')\n",
    "    if isinstance(df.columns, pd.MultiIndex):\n",
    "        df.columns = df.columns.get_level_values(0)\n",
    "    missing_cols = [c for c in REQUIRED_COLUMNS if c not in df.columns]\n",
    "    if missing_cols:\n",
    "        raise DataValidationError(f'Missing columns in {ticker}',\n",
    "            details={'missing': missing_cols})\n",
    "    if len(df) < MIN_REQUIRED_ROWS:\n",
    "        raise DataValidationError(f'Insufficient data for {ticker}',\n",
    "            details={'rows_found': len(df), 'minimum_required': MIN_REQUIRED_ROWS})\n",
    "    null_pct = df[REQUIRED_COLUMNS].isnull().mean()\n",
    "    violating = null_pct[null_pct > MAX_NULL_PCT]\n",
    "    if not violating.empty:\n",
    "        raise DataValidationError(f'Too many nulls in {ticker}',\n",
    "            details={'null_percentages': violating.to_dict()})\n",
    "    invalid_hl = df[df['High'] < df['Low']]\n",
    "    if not invalid_hl.empty:\n",
    "        raise DataValidationError(f'High < Low found in {ticker}',\n",
    "            details={'first_occurrence': str(invalid_hl.index[0])})\n",
    "    duplicates = df.index.duplicated().sum()\n",
    "    if duplicates > 0:\n",
    "        log.warning(f'Removing {duplicates} duplicate timestamps in {ticker}')\n",
    "        df = df[~df.index.duplicated(keep='last')]\n",
    "    rows_before = len(df)\n",
    "    df = df.dropna(subset=REQUIRED_COLUMNS)\n",
    "    dropped = rows_before - len(df)\n",
    "    if dropped > 0:\n",
    "        log.warning(f'Dropped {dropped} rows with nulls in {ticker}')\n",
    "    log.success(f'Validation passed for {ticker} | Clean rows: {len(df)}')\n",
    "    return df\n",
    "\n",
    "def save_raw_data(df, ticker, raw_path):\n",
    "    clean_ticker = ticker.replace('=X', '').replace('/', '')\n",
    "    output_dir = Path(raw_path)\n",
    "    output_dir.mkdir(parents=True, exist_ok=True)\n",
    "    file_path = output_dir / f'{clean_ticker}_raw.parquet'\n",
    "    try:\n",
    "        df.to_parquet(file_path, index=True)\n",
    "        log.success(f'Saved raw data to {file_path} | Rows: {len(df)}')\n",
    "    except Exception as e:\n",
    "        raise DataIngestionError(f'Failed to save raw data for {ticker}',\n",
    "            details={'path': str(file_path), 'error': str(e)})\n",
    "    return file_path\n",
    "\n",
    "def run_ingestion():\n",
    "    log.info('STARTING DATA INGESTION PIPELINE')\n",
    "    tickers = CONFIG['data']['pairs']\n",
    "    interval = CONFIG['data']['interval']\n",
    "    period_years = CONFIG['data']['period_years']\n",
    "    raw_path = CONFIG['data']['raw_path']\n",
    "    log.info(f'Tickers: {tickers} | Interval: {interval} | Period: {period_years} years')\n",
    "    results = {}\n",
    "    failed = []\n",
    "    for ticker in tickers:\n",
    "        log.info(f'Processing {ticker}...')\n",
    "        try:\n",
    "            raw_df = download_ohlcv(\n",
    "                ticker=ticker,\n",
    "                period_years=period_years,\n",
    "                interval=interval,\n",
    "            )\n",
    "            clean_df = validate_ohlcv(df=raw_df, ticker=ticker)\n",
    "            saved_path = save_raw_data(\n",
    "                df=clean_df,\n",
    "                ticker=ticker,\n",
    "                raw_path=raw_path,\n",
    "            )\n",
    "            results[ticker] = {\n",
    "                'status': 'success',\n",
    "                'rows': len(clean_df),\n",
    "                'path': str(saved_path),\n",
    "                'date_range': f'{clean_df.index.min().date()} to {clean_df.index.max().date()}',\n",
    "            }\n",
    "        except (DataIngestionError, DataValidationError) as e:\n",
    "            log.error(f'Failed to ingest {ticker}: {e}')\n",
    "            results[ticker] = {'status': 'failed', 'error': str(e)}\n",
    "            failed.append(ticker)\n",
    "    log.info('INGESTION SUMMARY')\n",
    "    for ticker, result in results.items():\n",
    "        if result['status'] == 'success':\n",
    "            log.success(f\"OK {ticker} | {result['rows']} rows | {result['date_range']}\")\n",
    "        else:\n",
    "            log.error(f\"FAILED {ticker} | {result['error']}\")\n",
    "    if len(failed) == len(tickers):\n",
    "        raise DataIngestionError('All tickers failed.', details={'failed': failed})\n",
    "    log.info('Data ingestion complete.')\n",
    "    return results\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    run_ingestion()\n",
]



# ── Write all files ─────────────────────────────────────────────
file_map = {
    'src/utils/logger.py':      logger_code,
    'src/utils/exceptions.py':  exceptions_code,
    'src/utils/config.py':      config_code,
    'src/ingestion/ingest.py':  ingest_code,


    'src/models/walk_forward.py': [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from dataclasses import dataclass\n",
    "from typing import List\n",
    "from src.utils.logger import log\n",
    "from src.utils.exceptions import BacktestError\n",
    "from src.utils.config import CONFIG\n",
    "\n",
    "@dataclass\n",
    "class WalkForwardFold:\n",
    "    fold_id: int\n",
    "    train: pd.DataFrame\n",
    "    val: pd.DataFrame\n",
    "    test: pd.DataFrame\n",
    "    train_start: pd.Timestamp\n",
    "    train_end: pd.Timestamp\n",
    "    test_end: pd.Timestamp\n",
    "\n",
    "    def __repr__(self):\n",
    "        return (\n",
    "            f'Fold {self.fold_id} | '\n",
    "            f'Train: {self.train_start.date()} to {self.train_end.date()} '\n",
    "            f'({len(self.train)} rows) | '\n",
    "            f'Val: {len(self.val)} rows | '\n",
    "            f'Test: {len(self.test)} rows'\n",
    "        )\n",
    "\n",
    "@dataclass\n",
    "class WalkForwardConfig:\n",
    "    train_window: int = 500\n",
    "    val_window: int = 63\n",
    "    test_window: int = 21\n",
    "    step_size: int = 21\n",
    "    holdout_pct: float = 0.20\n",
    "\n",
    "def generate_folds(df, config):\n",
    "    holdout_size = int(len(df) * config.holdout_pct)\n",
    "    tuning_zone = df.iloc[:-holdout_size]\n",
    "    holdout_zone = df.iloc[-holdout_size:]\n",
    "    log.info(\n",
    "        f'Data split | '\n",
    "        f'Tuning zone: {len(tuning_zone)} rows | '\n",
    "        f'Holdout: {len(holdout_zone)} rows '\n",
    "        f'({tuning_zone.index[-1].date()} to {holdout_zone.index[-1].date()})'\n",
    "    )\n",
    "    min_required = config.train_window + config.val_window + config.test_window\n",
    "    if len(tuning_zone) < min_required:\n",
    "        raise BacktestError(\n",
    "            'Insufficient data for walk-forward validation',\n",
    "            details={\n",
    "                'rows_available': len(tuning_zone),\n",
    "                'rows_required': min_required,\n",
    "                'suggestion': 'Reduce train_window or increase period_years in config'\n",
    "            }\n",
    "        )\n",
    "    folds = []\n",
    "    fold_id = 1\n",
    "    start = 0\n",
    "    while True:\n",
    "        train_end = start + config.train_window\n",
    "        val_end = train_end + config.val_window\n",
    "        test_end = val_end + config.test_window\n",
    "        if test_end > len(tuning_zone):\n",
    "            break\n",
    "        train = tuning_zone.iloc[start:train_end]\n",
    "        val = tuning_zone.iloc[train_end:val_end]\n",
    "        test = tuning_zone.iloc[val_end:test_end]\n",
    "        fold = WalkForwardFold(\n",
    "            fold_id=fold_id,\n",
    "            train=train,\n",
    "            val=val,\n",
    "            test=test,\n",
    "            train_start=train.index[0],\n",
    "            train_end=train.index[-1],\n",
    "            test_end=test.index[-1],\n",
    "        )\n",
    "        folds.append(fold)\n",
    "        log.debug(str(fold))\n",
    "        start += config.step_size\n",
    "        fold_id += 1\n",
    "    if not folds:\n",
    "        raise BacktestError(\n",
    "            'No valid folds generated',\n",
    "            details={'tuning_rows': len(tuning_zone), 'min_required': min_required}\n",
    "        )\n",
    "    log.success(f'Generated {len(folds)} walk-forward folds')\n",
    "    return folds\n",
    "\n",
    "def get_holdout(df, config):\n",
    "    holdout_size = int(len(df) * config.holdout_pct)\n",
    "    holdout = df.iloc[-holdout_size:]\n",
    "    log.info(\n",
    "        f'Holdout set retrieved | '\n",
    "        f'Rows: {len(holdout)} | '\n",
    "        f'Period: {holdout.index[0].date()} to {holdout.index[-1].date()}'\n",
    "    )\n",
    "    return holdout\n",
    "\n",
    "def get_feature_columns(df):\n",
    "    exclude = {'target', 'forward_return', 'Open', 'High', 'Low', 'Volume'}\n",
    "    features = [c for c in df.columns if c not in exclude]\n",
    "    log.debug(f'Feature columns ({len(features)}): {features}')\n",
    "    return features\n",
    ],

    'src/backtesting/backtest.py': [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from dataclasses import dataclass\n",
    "from typing import Tuple\n",
    "import json\n",
    "from src.utils.logger import log\n",
    "from src.utils.exceptions import BacktestError, SharpeThresholdError\n",
    "from src.utils.config import CONFIG\n",
    "\n",
    "@dataclass\n",
    "class BacktestResults:\n",
    "    ticker: str\n",
    "    sharpe_ratio: float\n",
    "    max_drawdown: float\n",
    "    total_return: float\n",
    "    win_rate: float\n",
    "    n_trades: int\n",
    "    avg_return_per_trade: float\n",
    "    passed_gate: bool\n",
    "\n",
    "    def __str__(self):\n",
    "        status = 'PASSED' if self.passed_gate else 'FAILED'\n",
    "        return (\n",
    "            f'Backtest Results [{self.ticker}] | {status}\\n'\n",
    "            f'  Sharpe Ratio:         {self.sharpe_ratio:.4f}\\n'\n",
    "            f'  Max Drawdown:         {self.max_drawdown:.2%}\\n'\n",
    "            f'  Total Return:         {self.total_return:.2%}\\n'\n",
    "            f'  Win Rate:             {self.win_rate:.2%}\\n'\n",
    "            f'  Number of Trades:     {self.n_trades}\\n'\n",
    "            f'  Avg Return per Trade: {self.avg_return_per_trade:.4%}\\n'\n",
    "        )\n",
    "\n",
    "    def to_dict(self):\n",
    "        return {\n",
    "            'ticker': self.ticker,\n",
    "            'sharpe_ratio': self.sharpe_ratio,\n",
    "            'max_drawdown': self.max_drawdown,\n",
    "            'total_return': self.total_return,\n",
    "            'win_rate': self.win_rate,\n",
    "            'n_trades': self.n_trades,\n",
    "            'avg_return_per_trade': self.avg_return_per_trade,\n",
    "            'passed_gate': self.passed_gate,\n",
    "        }\n",
    "\n",
    "def compute_sharpe_ratio(returns, risk_free_rate=0.0):\n",
    "    if len(returns) < 2:\n",
    "        return 0.0\n",
    "    excess = returns - risk_free_rate / 252\n",
    "    std = np.std(excess)\n",
    "    if std == 0:\n",
    "        return 0.0\n",
    "    return float(np.mean(excess) / std * np.sqrt(252))\n",
    "\n",
    "def compute_max_drawdown(cumulative_returns):\n",
    "    if len(cumulative_returns) < 2:\n",
    "        return 0.0\n",
    "    peak = cumulative_returns.expanding().max()\n",
    "    drawdown = (cumulative_returns - peak) / peak\n",
    "    return float(drawdown.min())\n",
    "\n",
    "def compute_win_rate(strategy_returns):\n",
    "    if len(strategy_returns) == 0:\n",
    "        return 0.0\n",
    "    wins = (strategy_returns > 0).sum()\n",
    "    return float(wins / len(strategy_returns))\n",
    "\n",
    "def signals_to_strategy_returns(predictions, actual_returns, transaction_cost=0.0002):\n",
    "    positions = np.where(predictions == 1, 1, -1)\n",
    "    position_changes = np.diff(positions, prepend=0)\n",
    "    costs = np.abs(position_changes) * transaction_cost\n",
    "    strategy_returns = positions * actual_returns - costs\n",
    "    return strategy_returns\n",
    "\n",
    "def run_backtest(\n",
    "    predictions,\n",
    "    actual_returns,\n",
    "    ticker,\n",
    "    risk_free_rate=None,\n",
    "    sharpe_threshold=None,\n",
    "    transaction_cost=0.0002,\n",
    "):\n",
    "    if risk_free_rate is None:\n",
    "        risk_free_rate = CONFIG['backtesting']['risk_free_rate']\n",
    "    if sharpe_threshold is None:\n",
    "        sharpe_threshold = CONFIG['backtesting']['sharpe_threshold']\n",
    "    log.info(f'Running backtest for {ticker} | Signals: {len(predictions)}')\n",
    "    if len(predictions) != len(actual_returns):\n",
    "        raise BacktestError(\n",
    "            'Predictions and returns length mismatch',\n",
    "            details={\n",
    "                'predictions_len': len(predictions),\n",
    "                'returns_len': len(actual_returns)\n",
    "            }\n",
    "        )\n",
    "    if len(predictions) < 30:\n",
    "        raise BacktestError(\n",
    "            'Insufficient data for meaningful backtest',\n",
    "            details={'n_samples': len(predictions), 'minimum': 30}\n",
    "        )\n",
    "    strategy_returns = signals_to_strategy_returns(\n",
    "        predictions, actual_returns, transaction_cost\n",
    "    )\n",
    "    cumulative = pd.Series((1 + strategy_returns).cumprod())\n",
    "    sharpe = compute_sharpe_ratio(strategy_returns, risk_free_rate)\n",
    "    max_dd = compute_max_drawdown(cumulative)\n",
    "    total_return = float(cumulative.iloc[-1] - 1)\n",
    "    win_rate = compute_win_rate(strategy_returns)\n",
    "    n_trades = int(np.sum(np.abs(np.diff(np.where(predictions == 1, 1, -1), prepend=0)) > 0))\n",
    "    avg_return = float(np.mean(strategy_returns))\n",
    "    passed = sharpe >= sharpe_threshold\n",
    "    results = BacktestResults(\n",
    "        ticker=ticker,\n",
    "        sharpe_ratio=sharpe,\n",
    "        max_drawdown=max_dd,\n",
    "        total_return=total_return,\n",
    "        win_rate=win_rate,\n",
    "        n_trades=n_trades,\n",
    "        avg_return_per_trade=avg_return,\n",
    "        passed_gate=passed,\n",
    "    )\n",
    "    log.info(str(results))\n",
    "    if passed:\n",
    "        log.success(\n",
    "            f'Backtest PASSED | '\n",
    "            f'Sharpe {sharpe:.4f} >= threshold {sharpe_threshold}'\n",
    "        )\n",
    "    else:\n",
    "        log.error(\n",
    "            f'Backtest FAILED | '\n",
    "            f'Sharpe {sharpe:.4f} < threshold {sharpe_threshold}'\n",
    "        )\n",
    "    return results\n",
    "\n",
    "def save_backtest_results(results, output_dir='logs'):\n",
    "    Path(output_dir).mkdir(exist_ok=True)\n",
    "    output_path = Path(output_dir) / f'backtest_{results.ticker}.json'\n",
    "    with open(output_path, 'w') as f:\n",
    "        json.dump(results.to_dict(), f, indent=2)\n",
    "    log.success(f'Backtest results saved to {output_path}')\n",
    "    return output_path\n",
    "\n",
    "def run_sharpe_gate(results):\n",
    "    sharpe_threshold = CONFIG['backtesting']['sharpe_threshold']\n",
    "    if not results.passed_gate:\n",
    "        raise SharpeThresholdError(\n",
    "            f'Model failed Sharpe gate for {results.ticker}',\n",
    "            details={\n",
    "                'achieved_sharpe': results.sharpe_ratio,\n",
    "                'required_sharpe': sharpe_threshold,\n",
    "                'shortfall': sharpe_threshold - results.sharpe_ratio,\n",
    "            }\n",
    "        )\n",
    "    log.success(\n",
    "        f'Sharpe gate PASSED for {results.ticker} | '\n",
    "        f'Sharpe: {results.sharpe_ratio:.4f}'\n",
    "    )\n",
    "    return True\n",
    ],

    '.github/workflows/ci_cd.yml': [
    "name: Forex Pipeline CI/CD\n",
    "\n",
    "on:\n",
    "  push:\n",
    "    branches: [main, develop]\n",
    "  pull_request:\n",
    "    branches: [main]\n",
    "\n",
    "jobs:\n",
    "  test:\n",
    "    name: Run Tests\n",
    "    runs-on: ubuntu-latest\n",
    "\n",
    "    steps:\n",
    "      - name: Checkout code\n",
    "        uses: actions/checkout@v4\n",
    "\n",
    "      - name: Set up Python 3.11\n",
    "        uses: actions/setup-python@v5\n",
    "        with:\n",
    "          python-version: '3.11'\n",
    "\n",
    "      - name: Cache dependencies\n",
    "        uses: actions/cache@v4\n",
    "        with:\n",
    "          path: ~/.cache/pip\n",
    "          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}\n",
    "          restore-keys: |\n",
    "            ${{ runner.os }}-pip-\n",
    "\n",
    "      - name: Install dependencies\n",
    "        run: |\n",
    "          python -m pip install --upgrade pip\n",
    "          pip install numpy==1.26.4\n",
    "          pip install pandas==2.2.2\n",
    "          pip install pyarrow==15.0.2\n",
    "          pip install scikit-learn==1.4.2\n",
    "          pip install lightgbm==4.3.0\n",
    "          pip install xgboost==2.0.3\n",
    "          pip install optuna==3.6.1\n",
    "          pip install mlflow==2.13.0\n",
    "          pip install loguru==0.7.2\n",
    "          pip install pyyaml==6.0.1\n",
    "          pip install python-dotenv==1.0.1\n",
    "          pip install pytest==8.2.0\n",
    "          pip install pytest-cov==5.0.0\n",
    "          pip install setuptools\n",
    "\n",
    "      - name: Install project\n",
    "        run: pip install -e .\n",
    "\n",
    "      - name: Run unit tests\n",
    "        run: |\n",
    "          pytest tests/ -v --cov=src --cov-report=term-missing\n",
    "\n",
    "  sharpe-gate:\n",
    "    name: Sharpe Ratio Gate\n",
    "    runs-on: ubuntu-latest\n",
    "    needs: test\n",
    "    if: github.ref == 'refs/heads/main'\n",
    "\n",
    "    steps:\n",
    "      - name: Checkout code\n",
    "        uses: actions/checkout@v4\n",
    "\n",
    "      - name: Set up Python 3.11\n",
    "        uses: actions/setup-python@v5\n",
    "        with:\n",
    "          python-version: '3.11'\n",
    "\n",
    "      - name: Install dependencies\n",
    "        run: |\n",
    "          python -m pip install --upgrade pip\n",
    "          pip install numpy==1.26.4\n",
    "          pip install pandas==2.2.2\n",
    "          pip install pyarrow==15.0.2\n",
    "          pip install scikit-learn==1.4.2\n",
    "          pip install lightgbm==4.3.0\n",
    "          pip install xgboost==2.0.3\n",
    "          pip install optuna==3.6.1\n",
    "          pip install mlflow==2.13.0\n",
    "          pip install loguru==0.7.2\n",
    "          pip install pyyaml==6.0.1\n",
    "          pip install python-dotenv==1.0.1\n",
    "          pip install setuptools\n",
    "\n",
    "      - name: Install project\n",
    "        run: pip install -e .\n",
    "\n",
    "      - name: Run Sharpe Gate\n",
    "        run: |\n",
    "          python -m src.utils.model_registry --ticker EURUSD\n",
    "        env:\n",
    "          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}\n",
    "\n",
    "      - name: Upload backtest results\n",
    "        if: always()\n",
    "        uses: actions/upload-artifact@v4\n",
    "        with:\n",
    "          name: backtest-results\n",
    "          path: logs/backtest_*.json\n",
    ],

    'tests/unit/test_backtest.py': [
    "import numpy as np\n",
    "import pytest\n",
    "from src.backtesting.backtest import (\n",
    "    compute_sharpe_ratio,\n",
    "    compute_max_drawdown,\n",
    "    compute_win_rate,\n",
    "    signals_to_strategy_returns,\n",
    "    run_backtest,\n",
    ")\n",
    "\n",
    "def test_sharpe_ratio_positive_returns():\n",
    "    returns = np.array([0.01] * 100)\n",
    "    sharpe = compute_sharpe_ratio(returns)\n",
    "    assert sharpe > 0\n",
    "\n",
    "def test_sharpe_ratio_zero_std():\n",
    "    returns = np.array([0.0] * 100)\n",
    "    sharpe = compute_sharpe_ratio(returns)\n",
    "    assert sharpe == 0.0\n",
    "\n",
    "def test_max_drawdown_is_negative():\n",
    "    import pandas as pd\n",
    "    cumulative = pd.Series([1.0, 1.1, 0.9, 0.95, 1.2])\n",
    "    dd = compute_max_drawdown(cumulative)\n",
    "    assert dd < 0\n",
    "\n",
    "def test_win_rate_all_positive():\n",
    "    returns = np.array([0.01] * 100)\n",
    "    wr = compute_win_rate(returns)\n",
    "    assert wr == 1.0\n",
    "\n",
    "def test_win_rate_all_negative():\n",
    "    returns = np.array([-0.01] * 100)\n",
    "    wr = compute_win_rate(returns)\n",
    "    assert wr == 0.0\n",
    "\n",
    "def test_strategy_returns_length():\n",
    "    preds = np.array([1, 0, 1, 1, 0])\n",
    "    actual = np.array([0.01, -0.01, 0.02, -0.005, 0.01])\n",
    "    result = signals_to_strategy_returns(preds, actual)\n",
    "    assert len(result) == len(preds)\n",
    "\n",
    "def test_run_backtest_returns_results():\n",
    "    np.random.seed(42)\n",
    "    preds = np.random.randint(0, 2, 200)\n",
    "    returns = np.random.normal(0.0003, 0.01, 200)\n",
    "    results = run_backtest(preds, returns, ticker='TEST')\n",
    "    assert results.ticker == 'TEST'\n",
    "    assert isinstance(results.sharpe_ratio, float)\n",
    "    assert isinstance(results.max_drawdown, float)\n",
    "    assert isinstance(results.win_rate, float)\n",
    "\n",
    "def test_run_backtest_insufficient_data():\n",
    "    from src.utils.exceptions import BacktestError\n",
    "    preds = np.array([1, 0, 1])\n",
    "    returns = np.array([0.01, -0.01, 0.02])\n",
    "    with pytest.raises(BacktestError):\n",
    "        run_backtest(preds, returns, ticker='TEST')\n",
    ],

'tests/unit/test_features.py': [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pytest\n",
    "from src.features.engineer import (\n",
    "    add_momentum_features,\n",
    "    add_trend_features,\n",
    "    add_volatility_features,\n",
    "    add_price_features,\n",
    "    add_target_variable,\n",
    ")\n",
    "\n",
    "def make_sample_df(n=200):\n",
    "    np.random.seed(42)\n",
    "    dates = pd.date_range('2020-01-01', periods=n, freq='B')\n",
    "    close = 1.1 + np.cumsum(np.random.normal(0, 0.001, n))\n",
    "    df = pd.DataFrame({\n",
    "        'Open':   close * 0.999,\n",
    "        'High':   close * 1.002,\n",
    "        'Low':    close * 0.998,\n",
    "        'Close':  close,\n",
    "        'Volume': np.random.randint(1000, 5000, n).astype(float),\n",
    "    }, index=dates)\n",
    "    return df\n",
    "\n",
    "def test_momentum_features_added():\n",
    "    from src.utils.config import CONFIG\n",
    "    df = make_sample_df()\n",
    "    cfg = CONFIG['features']\n",
    "    result = add_momentum_features(df.copy(), cfg)\n",
    "    assert 'rsi' in result.columns\n",
    "    assert 'macd' in result.columns\n",
    "    assert 'macd_signal' in result.columns\n",
    "\n",
    "def test_trend_features_added():\n",
    "    from src.utils.config import CONFIG\n",
    "    df = make_sample_df()\n",
    "    cfg = CONFIG['features']\n",
    "    result = add_trend_features(df.copy(), cfg)\n",
    "    assert 'sma_10' in result.columns\n",
    "    assert 'ema_12' in result.columns\n",
    "    assert 'adx' in result.columns\n",
    "\n",
    "def test_volatility_features_added():\n",
    "    from src.utils.config import CONFIG\n",
    "    df = make_sample_df()\n",
    "    cfg = CONFIG['features']\n",
    "    result = add_volatility_features(df.copy(), cfg)\n",
    "    assert 'atr' in result.columns\n",
    "    assert 'bb_width' in result.columns\n",
    "    assert 'bb_position' in result.columns\n",
    "\n",
    "def test_target_variable_binary():\n",
    "    df = make_sample_df()\n",
    "    df = add_price_features(df)\n",
    "    df = add_target_variable(df, horizon=5)\n",
    "    assert 'target' in df.columns\n",
    "    assert set(df['target'].unique()).issubset({0, 1})\n",
    "\n",
    "def test_no_lookahead_bias():\n",
    "    df = make_sample_df(n=100)\n",
    "    df = add_price_features(df)\n",
    "    df = add_target_variable(df, horizon=5)\n",
    "    assert df['target'].iloc[-1] in [0, 1]\n",
    "    assert len(df) == 95\n",
    ],

    'src/serving/app.py': [
    "import os\n",
    "import joblib\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "from fastapi import FastAPI, HTTPException\n",
    "from fastapi.middleware.cors import CORSMiddleware\n",
    "from pydantic import BaseModel\n",
    "from typing import Optional\n",
    "from src.utils.logger import log\n",
    "from src.utils.config import CONFIG\n",
    "from src.utils.exceptions import ModelLoadError, ModelPredictionError\n",
    "\n",
    "app = FastAPI(\n",
    "    title='Forex Signal Pipeline API',\n",
    "    description='Serves BUY/SELL/HOLD signals for forex pairs',\n",
    "    version='1.0.0',\n",
    ")\n",
    "\n",
    "app.add_middleware(\n",
    "    CORSMiddleware,\n",
    "    allow_origins=['*'],\n",
    "    allow_methods=['*'],\n",
    "    allow_headers=['*'],\n",
    ")\n",
    "\n",
    "LOADED_MODELS = {}\n",
    "\n",
    "class PredictionResponse(BaseModel):\n",
    "    ticker: str\n",
    "    signal: str\n",
    "    probability: float\n",
    "    direction: str\n",
    "    timestamp: str\n",
    "    model_version: str\n",
    "\n",
    "class HealthResponse(BaseModel):\n",
    "    status: str\n",
    "    models_loaded: list\n",
    "    timestamp: str\n",
    "\n",
    "class MetricsResponse(BaseModel):\n",
    "    ticker: str\n",
    "    sharpe_ratio: float\n",
    "    max_drawdown: float\n",
    "    total_return: float\n",
    "    win_rate: float\n",
    "\n",
    "def load_model(ticker):\n",
    "    clean_ticker = ticker.replace('=X', '').replace('/', '')\n",
    "    model_path = Path(f'models/ensemble/{clean_ticker}_ensemble.pkl')\n",
    "    if not model_path.exists():\n",
    "        raise ModelLoadError(\n",
    "            f'No trained model found for {ticker}',\n",
    "            details={'path': str(model_path)}\n",
    "        )\n",
    "    model = joblib.load(model_path)\n",
    "    log.success(f'Model loaded for {ticker} from {model_path}')\n",
    "    return model\n",
    "\n",
    "@app.on_event('startup')\n",
    "async def startup_event():\n",
    "    log.info('FastAPI starting up — loading models...')\n",
    "    tickers = CONFIG['data']['pairs']\n",
    "    for ticker in tickers:\n",
    "        try:\n",
    "            LOADED_MODELS[ticker] = load_model(ticker)\n",
    "            log.success(f'Loaded model for {ticker}')\n",
    "        except ModelLoadError as e:\n",
    "            log.warning(f'Could not load model for {ticker}: {e}')\n",
    "    log.info(f'Startup complete. Models loaded: {list(LOADED_MODELS.keys())}')\n",
    "\n",
    "@app.get('/health', response_model=HealthResponse)\n",
    "async def health_check():\n",
    "    return HealthResponse(\n",
    "        status='healthy',\n",
    "        models_loaded=list(LOADED_MODELS.keys()),\n",
    "        timestamp=datetime.utcnow().isoformat(),\n",
    "    )\n",
    "\n",
    "@app.get('/predict/{ticker}', response_model=PredictionResponse)\n",
    "async def predict(ticker: str):\n",
    "    log.info(f'Prediction request for {ticker}')\n",
    "    if ticker not in LOADED_MODELS:\n",
    "        try:\n",
    "            LOADED_MODELS[ticker] = load_model(ticker)\n",
    "        except ModelLoadError:\n",
    "            raise HTTPException(\n",
    "                status_code=404,\n",
    "                detail=f'No trained model available for {ticker}. Train the model first.'\n",
    "            )\n",
    "    try:\n",
    "        import yfinance as yf\n",
    "        raw_df = yf.download(\n",
    "            tickers=ticker,\n",
    "            period='6mo',\n",
    "            interval='1d',\n",
    "            auto_adjust=True,\n",
    "            progress=False,\n",
    "        )\n",
    "        if raw_df.empty:\n",
    "            raise HTTPException(\n",
    "                status_code=503,\n",
    "                detail=f'Could not fetch live data for {ticker}'\n",
    "            )\n",
    "        if isinstance(raw_df.columns, pd.MultiIndex):\n",
    "            raw_df.columns = raw_df.columns.get_level_values(0)\n",
    "        from src.features.engineer import build_features\n",
    "        feature_df = build_features(raw_df.copy(), ticker)\n",
    "        model = LOADED_MODELS[ticker]\n",
    "        signal, probability = model.predict(feature_df)\n",
    "        direction = 'UP' if signal == 'BUY' else 'DOWN' if signal == 'SELL' else 'NEUTRAL'\n",
    "        log.success(f'Prediction for {ticker}: {signal} ({probability:.3f})')\n",
    "        return PredictionResponse(\n",
    "            ticker=ticker,\n",
    "            signal=signal,\n",
    "            probability=round(probability, 4),\n",
    "            direction=direction,\n",
    "            timestamp=datetime.utcnow().isoformat(),\n",
    "            model_version='1.0.0',\n",
    "        )\n",
    "    except Exception as e:\n",
    "        log.error(f'Prediction failed for {ticker}: {e}')\n",
    "        raise HTTPException(status_code=500, detail=str(e))\n",
    "\n",
    "@app.get('/metrics/{ticker}', response_model=MetricsResponse)\n",
    "async def get_metrics(ticker: str):\n",
    "    import json\n",
    "    clean_ticker = ticker.replace('=X', '').replace('/', '')\n",
    "    results_path = Path(f'logs/backtest_{clean_ticker}.json')\n",
    "    if not results_path.exists():\n",
    "        raise HTTPException(\n",
    "            status_code=404,\n",
    "            detail=f'No backtest results found for {ticker}'\n",
    "        )\n",
    "    with open(results_path) as f:\n",
    "        data = json.load(f)\n",
    "    return MetricsResponse(\n",
    "        ticker=ticker,\n",
    "        sharpe_ratio=data['sharpe_ratio'],\n",
    "        max_drawdown=data['max_drawdown'],\n",
    "        total_return=data['total_return'],\n",
    "        win_rate=data['win_rate'],\n",
    "    )\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    import uvicorn\n",
    "    uvicorn.run(\n",
    "        'src.serving.app:app',\n",
    "        host=CONFIG['serving']['host'],\n",
    "        port=CONFIG['serving']['port'],\n",
    "        reload=True,\n",
    "    )\n",
    ],

    'docker/Dockerfile.api': [
    "FROM python:3.11-slim\n",
    "\n",
    "WORKDIR /app\n",
    "\n",
    "RUN apt-get update && apt-get install -y \\\n",
    "    build-essential \\\n",
    "    && rm -rf /var/lib/apt/lists/*\n",
    "\n",
    "COPY requirements.txt .\n",
    "\n",
    "RUN pip install --no-cache-dir --upgrade pip && \\\n",
    "    pip install --no-cache-dir numpy==1.26.4 && \\\n",
    "    pip install --no-cache-dir pyarrow==15.0.2 && \\\n",
    "    pip install --no-cache-dir -r requirements.txt\n",
    "\n",
    "COPY . .\n",
    "\n",
    "RUN pip install -e .\n",
    "\n",
    "EXPOSE 8000\n",
    "\n",
    "CMD [\"uvicorn\", \"src.serving.app:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n",
    ],

    'docker-compose.yml': [
    "version: '3.8'\n",
    "\n",
    "services:\n",
    "\n",
    "  api:\n",
    "    build:\n",
    "      context: .\n",
    "      dockerfile: docker/Dockerfile.api\n",
    "    container_name: forex-api\n",
    "    ports:\n",
    "      - '8000:8000'\n",
    "    volumes:\n",
    "      - ./models:/app/models\n",
    "      - ./data:/app/data\n",
    "      - ./logs:/app/logs\n",
    "      - ./configs:/app/configs\n",
    "    environment:\n",
    "      - MLFLOW_TRACKING_URI=http://mlflow:5000\n",
    "    depends_on:\n",
    "      - mlflow\n",
    "    restart: unless-stopped\n",
    "\n",
    "  mlflow:\n",
    "    image: python:3.11-slim\n",
    "    container_name: forex-mlflow\n",
    "    ports:\n",
    "      - '5000:5000'\n",
    "    volumes:\n",
    "      - ./mlruns:/mlruns\n",
    "    command: >\n",
    "      bash -c 'pip install mlflow==2.13.0 &&\n",
    "      mlflow server\n",
    "      --host 0.0.0.0\n",
    "      --port 5000\n",
    "      --backend-store-uri /mlruns'\n",
    "    restart: unless-stopped\n",
    "\n",
    "  dashboard:\n",
    "    build:\n",
    "      context: .\n",
    "      dockerfile: docker/Dockerfile.dashboard\n",
    "    container_name: forex-dashboard\n",
    "    ports:\n",
    "      - '8501:8501'\n",
    "    volumes:\n",
    "      - ./models:/app/models\n",
    "      - ./data:/app/data\n",
    "      - ./logs:/app/logs\n",
    "      - ./configs:/app/configs\n",
    "    environment:\n",
    "      - API_URL=http://api:8000\n",
    "    depends_on:\n",
    "      - api\n",
    "    restart: unless-stopped\n",
    ],


}

for filepath, lines in file_map.items():
    dirpath = os.path.dirname(filepath)
    if dirpath:
        os.makedirs(dirpath, exist_ok=True)
    with open(filepath, 'w', encoding='utf-8', newline='\n') as f:
        f.writelines(lines)
    print(f'Written: {filepath}')




print('Done. All files written cleanly.')